"""
Tekla Code Generator
Generates Tekla OpenAPI C# code from building schema
"""

import json
from typing import Dict
from pathlib import Path
from anthropic import Anthropic
from jinja2 import Template

from ..schema import BuildingSchema
from ..utils import get_logger, Config

logger = get_logger(__name__)


class TeklaCodeGenerator:
    """
    Generate Tekla OpenAPI C# code from BuildingSchema
    """

    def __init__(self):
        self.logger = logger
        self.client = Anthropic(api_key=Config.ANTHROPIC_API_KEY)
        self.template_dir = Config.CODE_TEMPLATE_DIR

    def generate(self, schema: BuildingSchema) -> str:
        """
        Generate complete Tekla C# code

        Args:
            schema: Building schema

        Returns:
            Complete C# code as string
        """
        self.logger.info("Generating Tekla code")

        try:
            # Generate using LLM
            code = self._generate_with_llm(schema)

            self.logger.info("Code generation complete", lines=len(code.split('\n')))

            return code

        except Exception as e:
            self.logger.error("Code generation failed", error=str(e))
            raise

    def _generate_with_llm(self, schema: BuildingSchema) -> str:
        """
        Generate code using LLM

        Args:
            schema: Building schema

        Returns:
            C# code
        """
        prompt = self._build_generation_prompt(schema)

        response = self.client.messages.create(
            model=Config.DEFAULT_LLM_MODEL,
            max_tokens=Config.MAX_TOKENS,
            temperature=Config.TEMPERATURE,
            messages=[{
                "role": "user",
                "content": prompt
            }]
        )

        code = response.content[0].text

        # Extract code from markdown if present
        if "```csharp" in code:
            code = code.split("```csharp")[1].split("```")[0]
        elif "```cs" in code:
            code = code.split("```cs")[1].split("```")[0]
        elif "```" in code:
            code = code.split("```")[1].split("```")[0]

        return code.strip()

    def _build_generation_prompt(self, schema: BuildingSchema) -> str:
        """Build LLM prompt for code generation"""

        schema_json = schema.model_dump_json(indent=2)

        return f"""
You are an expert Tekla Structures OpenAPI developer.

Generate complete, production-ready C# code to create this building model:

BUILDING SCHEMA:
{schema_json}

REQUIREMENTS:

1. Structure:
   - Use namespace "AutoGeneratedModel"
   - Import: Tekla.Structures.Model, Tekla.Structures.Geometry3d
   - Main class: "ModelBuilder"
   - Entry point: Main() method
   - Methods: CreateGrid(), CreateColumns(), CreateBeams(), CreateConnections()

2. Implementation:
   a) Check Tekla connection
   b) Create grid system
   c) Create all columns with base plates
   d) Create all beams
   e) Create connections
   f) Commit changes

3. Tekla API conventions:
   - All coordinates in millimeters
   - Profile strings use asterisk (*) not x: "UC305*305*198"
   - Position enums: Position.DepthEnum, Position.PlaneEnum
   - Insert() each object and check return value

4. Code quality:
   - Try-catch blocks for error handling
   - Console.WriteLine for progress
   - Comments for major sections
   - Descriptive variable names

5. Example column creation:
```csharp
Beam column = new Beam();
column.StartPoint = new Point(0, 0, 0);
column.EndPoint = new Point(0, 0, 8000);
column.Profile.ProfileString = "UC305*305*198";
column.Material.MaterialString = "S355";
column.Position.Depth = Position.DepthEnum.MIDDLE;
column.Insert();
```

Generate the complete C# code now. Return ONLY the code, no explanations.
"""

    ### TODO: USER MUST FILL THIS SECTION
    # Add custom code generation features:
    # - Template-based generation (Jinja2)
    # - RAG system for Tekla API docs
    # - Code optimization
    # - Custom component generation


if __name__ == "__main__":
    print("Tekla Code Generator ready.")
