"""
Code Generation Prompts
LLM prompts for Tekla C# code generation
"""

TEKLA_CODE_GEN_PROMPT = """
You are an expert Tekla Structures OpenAPI developer.

Generate complete, production-ready C# code to create this building model:

BUILDING SCHEMA:
{schema_json}

REQUIREMENTS:

1. Structure:
   - Namespace: "AutoGeneratedModel"
   - Imports: Tekla.Structures.Model, Tekla.Structures.Geometry3d
   - Main class: "ModelBuilder"
   - Entry point: Main() method

2. Implementation order:
   a) Check Tekla connection
   b) Create grid system
   c) Create all columns with base plates
   d) Create all beams
   e) Commit changes

3. Tekla API conventions:
   - All coordinates in millimeters
   - Profile strings use asterisk (*): "UC305*305*198"
   - Position enums: Position.DepthEnum.MIDDLE, etc.

4. Code quality:
   - Error handling
   - Progress logging
   - Comments

Generate the complete C# code now. Return ONLY the code.
"""

### TODO: USER MUST FILL THIS SECTION
# Add prompts for:
# - Different connection types
# - Special components
# - Optimization
